[build]
  command = "npm run build"
  publish = "dist"

[dev]
  port = 3000
  framework = "vite"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
